language: cpp
dist: trusty
sudo: false

notifications:
    email: false

before_install:
    - chmod 600 tests/ezio.pem
    - eval $(ssh-agent)
    - ssh-add tests/ezio.pem
    - bash tests/before_install.sh

install:
    - bash tests/install.sh

before_script:
    - bash tests/before_script.sh

script:
    - bash tests/script.sh

after_success:
    - bash tests/before_deploy.sh
    - bash tests/deploy.sh
